config/routes.rb
Rails.application.routes.draw do
  scope "comedynight" do 
    resources :tickets, only: [:index, :new]

    resources :sales, except: [:show]

    resources :users
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get 'sign_in' => redirect('/users/auth/google_oauth2'), :as => :new_user_session
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end

    get '/dashboard', to: 'tickets#dashboard', as: 'dashboard'
    get '/tickets/:id/paid', to: 'tickets#paid', as: 'paid'
    get '/tickets/:id/blocked', to: 'tickets#blocked', as: 'blocked'
    get '/',to: 'visitors#index'
  end
  root to: 'visitors#index'
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id         :integer          not null, primary key
#  sale_id    :integer
#  user_id    :integer
#  paid       :boolean
#  blocked    :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Ticket < ActiveRecord::Base
  belongs_to :sale  
  validate :validate_ticket_count, :on => :create
  validate :validate_user, :on => :create
  validate :validate_time, :on => :create
  def validate_ticket_count
     if self.sale.tickets.count >= self.sale.quantity
       errors.add(:id, 'Error - Max ticket limit reached for this sale')
     end
  end

  def validate_user
    unless Ticket.where(user_id: self.user_id).empty?
       errors.add(:id, 'Error - You have already booked a ticket')
     end
  end

  def validate_time
    unless self.sale.start < Time.now and Time.now < self.sale.end
      errors.add(:id, 'Error - Sale not running')
    end
  end
  belongs_to :user
  def status
  	if paid
  		"Paid"
  	elsif blocked
  		"Blocked"
  	else
  		"Booked"
  	end
  end
   def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:paid, :blocked]
  after_action :verify_authorized
  before_filter :authenticate_user!

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
    authorize @tickets
  end


  # GET /tickets/new
  def new
    @ticket = Ticket.new
    authorize @ticket
    if current_sale?
      @ticket.user = current_user
      @ticket.sale = current_sale
      if @ticket.save
        redirect_to dashboard_path
      else
        flash[:error] = "Sorry all tickets sold out"
        redirect_to dashboard_path
      end
    else
      redirect_to dashboard_path
    end
  end

  #GET /tickets/:id/paid
  def paid
    authorize @ticket
    @ticket.paid = true
    @ticket.save!
    redirect_to tickets_path
  end

  #GET /tickets/:id/blocked
  def blocked
    authorize @ticket
    @ticket.blocked = true
    @ticket.save!
    redirect_to tickets_path
  end

  #get /dashboard
  def dashboard
    @tickets = Ticket.all
    authorize @tickets
    @ticket = current_user.ticket
    render(layout: false)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/dashboard.html.erb
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js dash" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Esya IIITD | Comedy Night</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <link href="favicon.ico" rel="shortcut icon" />
        <link href="apple-touch-icon-precomposed.png" rel="apple-touch-icon-precomposed" />
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <%= stylesheet_link_tag 'app', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= csrf_meta_tags %>        
        <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    </head>
    <body>
      <!--[if lt IE 8]>
          <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
      <![endif]-->

   
    <div class="container-fluid">
        <div><%= image_tag("Logo.png", class: "logo-tedx-dash img-responsive") %></div>
        <% if flash[:error] %>
           <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div,  flash[:error] , :id => "flash_error" %>
          </div>
        <% end %>
        <hr style="border-color:white">
      <div class="center"><%= current_user %><%= link_to "Logout",destroy_user_session_path,:class => "btn" %></div>
      <hr style="border-color:white;padding: 0;margin: 0">
      <h1 class="center">Ticket Booking for Esya IIITD Comedy Night - 21st August 2015.</h1>
      <hr>
      <% if current_sale? and @ticket.nil? %>
        <h2 class="center">Tickets Left: <%=tickets_left%></h2>
        <% if tickets_left > 0 %>
        <div class="row"><div class="center col-md-12"><div id="bookbutton">BOOK</div></div></div>
        <% end %>
      <% elsif not @ticket.nil? %>
        <h2 class="center">Your Ticket Status: <%= @ticket.status %></h2>
      <% else %>
        <% if future_sale.nil? %>
          <h2 class="center">No sales in near future. Keep visiting our Facebook page for further updates</h2>
        <% else %>
          <h2 class="center">NEXT SALE ON: <%= future_sale.start.to_s(:short) %></h2>
          <ul id="example">
            <li><span class="days">00</span><p class="days_text">Days</p></li>
            <li class="seperator">:</li>
            <li><span class="hours">00</span><p class="hours_text">Hours</p></li>
            <li class="seperator">:</li>
            <li><span class="minutes">00</span><p class="minutes_text">Minutes</p></li>
            <li class="seperator">:</li>
            <li><span class="seconds">00</span><p class="seconds_text">Seconds</p></li>
          </ul>
          <script type="text/javascript">
            $(document).ready(function(){
              $('#example').countdown({
              date: '<%= future_sale.start.utc.strftime("%m/%d/%Y %H:%M:%S")%>'
              }, function () {
                location.reload();
              });
            });
          </script>
        <% end %>
      <% end %>
      <hr>
      <h3 class="center">Previously Booked Tickets</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Sale</th>
            <th>User</th>
            <th>Status</th>
            <th>Time</th>
          </tr>
        </thead>

        <tbody>
          <% @tickets.each do |ticket| %>
            <tr>
              <td><%= ticket.sale %></td>
              <td><%= ticket.user%></td>
              <td><%= ticket.status %></td>
              <td><%= ticket.created_at.to_s(:short)%></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

    </body>
    <script type="text/javascript">
      $(document).ready(function(){
        $('#bookbutton').click(function(){
           window.location.href = "/comedynight/tickets/new" ;
        });

      });
    </script>
</html>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Sale</th>
      <th>User</th>
      <th>Status</th>
      <th>Time</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.sale %></td>
        <td><%=link_to ticket.user , ticket.user%></td>
        <td><%= ticket.status %></td>
        <td><%= ticket.created_at.to_s(:short) %></td>
        <td><%= link_to 'Paid', paid_path(ticket), :class => "btn btn-sm btn-primary" unless ticket.paid %></td>
        <td><%= link_to 'Blocked', blocked_path(ticket), :class => "btn btn-sm btn-primary" unless ticket.blocked %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>