config/routes.rb
Rails.application.routes.draw do
  scope "comedynight" do 
    resources :tickets, only: [:index, :new]

    resources :sales, except: [:show]

    resources :users
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get 'sign_in' => redirect('/users/auth/google_oauth2'), :as => :new_user_session
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end

    get '/dashboard', to: 'tickets#dashboard', as: 'dashboard'
    get '/tickets/:id/paid', to: 'tickets#paid', as: 'paid'
    get '/tickets/:id/blocked', to: 'tickets#blocked', as: 'blocked'
    get '/',to: 'visitors#index'
  end
  root to: 'visitors#index'
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id         :integer          not null, primary key
#  start      :datetime
#  end        :datetime
#  quantity   :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sale < ActiveRecord::Base
  belongs_to :user
  has_many :tickets, dependent: :destroy
  validates :quantity, :presence => true
  validates :end, :presence => true
  validates :start, :presence => true
  
  def to_s
    "Sale on " + self.start.to_s(:short) +" for "+ self.quantity.to_s + " tickets"
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!
  after_action :verify_authorized

  #Allow all actions, pundit ensures admin user, store current_user as creator

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    authorize  @sales
  end


  # GET /sales/new
  def new
    @sale = Sale.new
    authorize  @sale
  end

  # GET /sales/1/edit
  def edit
    authorize  @sale
  end

  # POST /sales
  def create
    @sale = Sale.new(sale_params)
    authorize  @sale
    @sale.user = current_user
    respond_to do |format|
      if @sale.save
        format.html { redirect_to sales_url, notice: 'Sale was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /sales/1
  def update
    authorize  @sale
    @sale.user ||= current_user
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sales_url, notice: 'Sale was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /sales/1
  def destroy
    authorize  @sale
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:start, :end, :quantity)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start, :as => :datetime_picker , label: "Start" %>
    <%= f.input :end , :as => :datetime_picker%>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script type="text/javascript">
    $('.datetimepicker').datetimepicker();
</script>

app/views/sales/edit.html.erb
<h1>Edit Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Start</th>
      <th>End</th>
      <th>Ticket quantity</th>
      <th>Created By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.start.to_s(:short) %></td>
        <td><%= sale.end.to_s(:short) %></td>
        <td><%= sale.quantity %></td>
        <td><%= sale.user %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) , :class => "btn btn-sm btn-warning"%></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="center">
<%= link_to 'New Sale', new_sale_path, :class => "btn btn-lg btn-success" %>
</div>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>