config/routes.rb
Rails.application.routes.draw do
  scope "comedynight" do 
    resources :tickets, only: [:index, :new]

    resources :sales, except: [:show]

    resources :users
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    devise_scope :user do
      get 'sign_in' => redirect('/users/auth/google_oauth2'), :as => :new_user_session
      get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
    end

    get '/dashboard', to: 'tickets#dashboard', as: 'dashboard'
    get '/tickets/:id/paid', to: 'tickets#paid', as: 'paid'
    get '/tickets/:id/blocked', to: 'tickets#blocked', as: 'blocked'
    get '/',to: 'visitors#index'
  end
  root to: 'visitors#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Esya IIITD', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <!-- <li><%# link_to 'Admin', '/admin' %></li> -->
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Tickets', tickets_path %></li>
    <li><%= link_to 'Sales', sales_path %></li>
  <% else %>
  <% end %>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Sign out', destroy_user_session_path %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
]<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Esya IIITD | Comedy Night" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Esya" %>">
    <%= stylesheet_link_tag 'app', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%# render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>